### ISSUE TITLE
Add `[[` method for `polars_data_frame`

### ISSUE THREAD

**Issue by shikokuchuo** [pola-rs/r-polars#1441]
I came across this (exploring why mirai's row-wise multiple map is currently failing for polars objects):

``` r
mtcars[[1]]
#>  [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
#> [16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
#> [31] 15.0 21.4

data.table::as.data.table(mtcars)[[1]]
#>  [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
#> [16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
#> [31] 15.0 21.4

polars::as_polars_df(mtcars)[[1]]
#> Error in polars::as_polars_df(mtcars)[[1]]: wrong arguments for subsetting an environment
```

<sup>Created on 2025-07-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

It would perhaps make sense to add a `[[` method for polars data frames?

(note also that in base R `mtcars[[1]]` is an order of magnitude faster than `mtcars[, 1, drop = TRUE]`)

**Comment by eitsupi** [comment]
IIUC, given that `[[` generally corresponds to `$`, I'm worried that adding this will complicate things.

However, looking at the arrow package, it is implemented as follows, so it might be worth implementing it in the same way.

```r
> arrow:::`[[.ArrowTabular`
function (x, i, ...) 
{
    if (is.character(i)) {
        x$GetColumnByName(i)
    }
    else if (is.numeric(i)) {
        x$column(i - 1)
    }
    else {
        stop("'i' must be character or numeric, not ", class(i), 
            call. = FALSE)
    }
}
```

**Comment by eitsupi** [comment]
@shikokuchuo I've released 1.0.1 including #1442, so could you test with that version? Thanks!

**Comment by shikokuchuo** [comment]
The method you implemented works fine!

I realise that what I wanted still doesn't work... but that's probably not something you need to solve on your side.
Basically I notice that there's also not a `[[` method for Polars Series. But then, there isn't for Arrow arrays either.

What's the idiomatic way of extracting a single element, or do we just convert to an R vector at this point?
